### ISSUE TITLE
Docker mmpdb.py error

### ISSUE THREAD

**Issue by MKCarter** [Merck/matcher#1]
Hey,

Trying to run this, but I seem to be unable to run the mmpdb.py when running the `docker compose up `command. This is the error I am obtaining:

```
matcher-backend-1   | python: can't open file '/opt/./mmpdb/mmpdb.py': [Errno 2] No such file or directory
matcher-backend-1   | ERROR conda.cli.main_run:execute(49): `conda run python ./mmpdb/mmpdb.py fragment ./initialize_db/quick_structures.smi -o ./initialize_db/quick_structures.fragments --cut-smarts matcher_alpha` failed. (See above for error)
matcher-backend-1 exited with code 1
```

Do you have any thoughts on how to fix this?

**Comment by hooveran** [comment]
Hey @MKCarter,

It seems like you may not have downloaded the required mmpdb submodule. You can check whether this is the case by looking in the matcher/backend/mmpdb directory, in your local matcher repository.

The contents of this mmpdb directory (submodule) are not automatically downloaded when cloning the matcher repository; these additional steps are necessary: 

1. Navigate to your local matcher repository (the parent matcher folder)
2. Execute `git submodule init`, and then `git submodule update`. This should download all the mmpdb code into the location matcher/backend/mmpdb

The below commands are only necessary if you've already run docker-compose, and you want to update your docker setup with the new code. If you hadn't previously run docker-compose, the below steps wouldn't be necessary.

3. Rebuild your local docker images to incorporate this newly downloaded code: `docker-compose build` (this command comprehensively rebuilds all images from source, although it is likely that only the backend container needs to be rebuilt)
4. Launch a fresh set of containers from the updated images: `docker-compose up --force-recreate`

Please let us know if there are further issues. Thanks!
