### ISSUE TITLE
start error "Service 'database' failed to build : Build failed"

### ISSUE THREAD

**Issue by tanyingjia** [Merck/matcher#4]
my ubuntu version is 18.04,docker version is 23.0.3, docker-compose version is 1.29.2.
I have already install matcher through your tutorial.
$ git clone https://github.com/Merck/matcher.git
$ cd matcher
$ sudo systemctl start docker
$ git submodule init
$ git submodule update
$ sudo docker-compose up
However. when running the last step, an error was encountered.

user@user-b:/mnt/***/matcher$ sudo docker-compose up
Building database
 [+] Building 25.8s (3/3) FINISHED                                               
  => [internal] load .dockerignore                                          0.0s
  => => transferring context: 2B                                            0.0s
  => [internal] load build definition from Dockerfile                       0.0s
  => => transferring dockerfile: 251B                                       0.0s
  => ERROR [internal] load metadata for docker.io/library/postgres:13      25.8s
 ------
  > [internal] load metadata for docker.io/library/postgres:13:
 ------
 Dockerfile:1
 --------------------
    1 | >>> FROM postgres:13
    2 |     
    3 |     # Install "rdkit" PostgreSQL extension
 --------------------
 ERROR: failed to solve: error getting credentials - err: exit status 1, out: `Error calling StartServiceByName for 
 org.freedesktop.secrets: Timeout was reached`
 ERROR: Service 'database' failed to build : Build failed

I have installed rdkit-postgresql.
What should I do in this situation?

**Comment by hooveran** [comment]
Hi @tanyingjia,

Based on a google search of your error messages, it seems like there is an issue with your docker config, potentially including the interaction between docker and your keyring. As a starting point, I'd suggest trying the actions suggested in the answers sections of the below stackoverflow posts involving your errors:

https://stackoverflow.com/questions/66912085/why-is-docker-compose-failing-with-error-internal-load-metadata-suddenly

https://stackoverflow.com/questions/50696747/docker-login-timeout-on-ubuntu-error-calling-startservicebyname-for-org-freedes

https://stackoverflow.com/questions/58533737/error-saving-credentials-error-storing-credentials-timeout-was-reached

**Comment by hooveran** [comment]
Closing this issue, please feel free to open another issue if needed.
