### ISSUE TITLE
Issue when using my own data: psycopg2.errors.DuplicateTable: relation "dataset" already exists

### ISSUE THREAD

**Issue by hnisonoff** [Merck/matcher#6]
I am getting the following errors:

```backend_1   | Started indexing at time = 1684792578.250812
backend_1   | Finished loading fragments, seconds taken = 0.0056688785552978516
backend_1   | Starting to find pairs at 1684792578.256481
backend_1   |     commandline.main()
backend_1   |   File "/opt/mmpdb/mmpdblib/commandline.py", line 1089, in main
backend_1   |     parsed_args.command(parsed_args.subparser, parsed_args)
backend_1   |   File "/opt/mmpdb/mmpdblib/commandline.py", line 393, in index_command
backend_1   |     do_index.index_command(parser, args)
backend_1   |   File "/opt/mmpdb/mmpdblib/do_index.py", line 203, in index_command
backend_1   |     with index_algorithm.open_mmpa_writer(args.output, format=args.out,
backend_1   |   File "/opt/mmpdb/mmpdblib/index_algorithm.py", line 1333, in open_mmpa_writer
backend_1   |     index_writer = index_writers.open_postgres_index_writer(destination, title)
backend_1   |   File "/opt/mmpdb/mmpdblib/index_writers.py", line 741, in open_postgres_index_writer
backend_1   |     schema.create_schema_for_postgres(db, schema_name=schema_name)
backend_1   |   File "/opt/mmpdb/mmpdblib/schema.py", line 233, in create_schema_for_postgres
backend_1   |     _execute_sql(c,
backend_1   |   File "/opt/mmpdb/mmpdblib/schema.py", line 200, in _execute_sql
backend_1   |     c.execute(statement)
backend_1   | psycopg2.errors.DuplicateTable: relation "dataset" already exists
backend_1   |
backend_1   | ERROR conda.cli.main_run:execute(47): `conda run python ./mmpdb/mmpdb.py index ./initialize_db/test.fragments -o public$postgres` failed. ```

**Comment by hooveran** [comment]
@hnisonoff

I think this error is caused when docker uses a DB volume with data from a previously-used dataset.

To fix, I'd recommend the following steps, if you haven't tried this already in this order:

`docker-compose down --volumes` # This should tell docker to get rid of saved data associated with the DB service
`docker-compose build backend` # This may not be necessary but it shouldn't hurt
`docker-compose up --force-recreate` # Launch new containers from scratch with new data

Let me know what happens - thanks!

**Comment by hnisonoff** [comment]
Thank you @hooveran !

This seemed to fix the error. However, when I open the web app I am getting the following message when I click on "select property"

```
No properties have been loaded to the database.
Please use mmpdb loadprops to load properties,
then reload the page.
```

The logs seem to suggest that the properties were loaded:


```
backend_1   | Matcher-specific postgres extension took (seconds): 1.349
backend_1   | Started loadprops_command at 2023-05-22 23:16:06
backend_1   | args
backend_1   | Namespace(quiet=False, databases=['public$postgres'], properties='./initialize_db/test_props.tsv', metadata=None, command=<function loadprops_command at 0x7f3c6dbdbee0>, subparser=ArgumentParser(prog='mmpdb.py loadprops', usage=None, description=None, formatter_class=<class 'argparse.RawDescriptionHelpFormatter'>, conflict_handler='error', add_help=True))
backend_1   | Reconnecting in loadprops_command at: 2023-05-22 23:16:06
backend_1   | Using dataset: MMPs from './initialize_db/test.fragments'
backend_1   | Reading properties from './initialize_db/test_props.tsv'
backend_1   | Read 1 properties for 126 compounds from './initialize_db/test_props.tsv'
backend_1   |
backend_1   | No metadata file was passed with the option --metadata <file>.
backend_1   | In this case, all property values displayed in the UI will be identical to those stored in the database.
backend_1   | All property changes will be represented as deltas by default in the UI.
backend_1   |
backend_1   | 2 compounds from './initialize_db/test_props.tsv' are not in the dataset at 'public$postgres'
backend_1   | Finished downloading compound_property rows at 2023-05-22 23:16:06
backend_1   | Starting compound_property writes for ec50_cleaned at 2023-05-22 23:16:06
backend_1   | Imported 124 'ec50_cleaned' records (124 new, 0 updated).
```

**Comment by hooveran** [comment]
@hnisonoff

Could you confirm that you are seeing the "No properties" message in the browser, even if you only navigate to localhost:8000 after observing the below message in the docker-compose console, which indicates that setup is complete?

`matcher-backend-1   | INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:8001 (Press CTRL+C to quit)`

I reproduce your error if I navigate to localhost:8000 before observing the above message.

If the error persists, what would help to continue debugging is if you could share the browser's javascript error messages, by right-clicking on the page, choosing "Inspect" in the right-click dropdown, then clicking "Console" at the top of the panel. Below is what I observe when reproducing your error. The output from the docker-compose console could also be helpful.

![image](https://github.com/Merck/matcher/assets/111536382/d2731a26-4dbb-4005-87ce-eb1709f354ac)

**Comment by nffaruk** [comment]
Hi, if there is an existing database container, is it possible to append new data that's processed after recreation and initialization of just the backend container pointing to just the new data in its startup initialize db script? i.e. avoid the `psycopg2.errors.DuplicateTable: relation "dataset" already exists` error through functionality to add to the existing dataset. This way we don't have to spend increasingly longer times preprocessing the entire dataset each time the backend is recreated.

**Comment by hooveran** [comment]
Hi @nffaruk , if I understand correctly, your use case involves having new compounds/data, and wanting to add MMPs/etc. based on these new compounds/data to a currently existing database, without recreating the entire database from scratch.

Although we want this feature, it has not been implemented to my knowledge.

I think the mmpdb developers have accelerated database building through parallelizing the `mmpdb index` command (which finds MMPs and creates the database), but it's not clear how much overall time savings this gains, and it's in a different fork of the mmpdb code, yet to be integrated to ours.
